export const ActionTypes = {
  SET_RECIPE: "SET_RECIPE",
  SET_FILTERED_RECIPE: "SET_FILTERED_RECIPE",
  SET_VEG: "SET_VEG",
  SET_NONVEG: "SET_NONVEG",
  SET_SEARCH: "SET_SEARCH",
  SET_DARK: "SET_DARK",
  SET_COUNT:"SET_COUNT",
  ADD_NEW_RECIPE:"ADD_NEW_RECIPE",
  DELETE_RECIPE:"DELETE_RECIPE",
  UPDATE_RECIPE:"UPDATE_RECIPE",
  SET_LIKED_RECIPE:"SET_LIKED_RECIPE"
};
